{
  "hash": "c24fd3e7bc54f94599a78b78a40b1779",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 3\"\nsubtitle: \"Spatio-temporal point pattern analysis\"\nauthor: \"Le Truong Chinh\"\ndate: \"7 September 2026\"\ndescription: \"An executed ISSS626 exercise analysing the location and timing of forest fire events in Kepulauan Bangka Belitung.\"\ntitle-block-banner: true\npage-layout: article\ntoc: true\ntoc-depth: 3\ncode-overflow: wrap\nformat:\n  html:\n    code-fold: false\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  message: false\n  fig-align: center\n  fig-width: 8\n  fig-height: 5.5\n---\n\n::: {.exercise-lead}\nThis exercise examines forest fire events recorded in Kepulauan Bangka Belitung during 2023. I map the events over time, estimate their changing density, and check whether they cluster across both space and time.\n:::\n\n## 1. What I am looking at\n\nA spatio-temporal point pattern records both where and when events happen. Here, each point is a forest fire detected by the MODIS sensor. I want to see whether the fire locations are spread evenly or whether they form concentrations that change over the year.\n\nTwo datasets are used:\n\n- `forestfires.csv`, containing the locations and dates of 741 detected fire events; and\n- `Kepulauan_Bangka_Belitung`, containing the administrative boundaries of the study area.\n\n## 2. Loading the R packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spatstat, sparr, \n               tmap, stpp, tidyverse,\n               animation)\n```\n:::\n\n\n## 3. Preparing the study area\n\n### 3.1 Importing the boundary\n\nFirst, I import the original boundary layer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb <- st_read(dsn=\"chap06/data/rawdata\",\n               layer = \"Kepulauan_Bangka_Belitung\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Kepulauan_Bangka_Belitung' from data source \n  `D:\\smu\\study\\GIS\\chap06\\data\\rawdata' using driver `ESRI Shapefile'\nSimple feature collection with 298 features and 27 fields\nGeometry type: POLYGON\nDimension:     XYZ\nBounding box:  xmin: 105.1085 ymin: -3.116593 xmax: 106.8488 ymax: -1.501603\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nThe revised code combines the individual administrative areas into one study boundary, removes any extra Z or M coordinates, and changes the coordinate system to UTM Zone 48S. A projected coordinate system is needed because the following analysis uses distance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_sf <- st_read(dsn=\"chap06/data/rawdata\",\n               layer = \"Kepulauan_Bangka_Belitung\") %>%\n  st_union() %>%\n  st_zm(drop = TRUE, what = \"ZM\") %>%\n  st_transform(crs = 32748)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Kepulauan_Bangka_Belitung' from data source \n  `D:\\smu\\study\\GIS\\chap06\\data\\rawdata' using driver `ESRI Shapefile'\nSimple feature collection with 298 features and 27 fields\nGeometry type: POLYGON\nDimension:     XYZ\nBounding box:  xmin: 105.1085 ymin: -3.116593 xmax: 106.8488 ymax: -1.501603\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n### 3.2 Creating the observation window\n\n`as.owin()` changes the study boundary into the window format used by `spatstat`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_owin <- as.owin(kbb_sf)\nkbb_owin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwindow: polygonal boundary\nenclosing rectangle: [512066.8, 705559.4] x [9655398, 9834006] units\n```\n\n\n:::\n:::\n\n\nThe class check confirms that the conversion worked.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(kbb_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"owin\"\n```\n\n\n:::\n:::\n\n\n## 4. Preparing the forest fire data\n\nThe CSV is imported, converted from longitude and latitude into an `sf` point layer, and projected to the same coordinate system as the study area.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- read_csv(\"chap06/data/rawdata/forestfires.csv\") %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"),\n                       crs = 4326) %>%\n  st_transform(crs = 32748)\n```\n:::\n\n\nI then create three simple time fields: day of year, month number, and month name. The month fields are used to compare the fire pattern over the year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- fire_sf %>% \n  mutate(DayofYear = yday(acq_date)) %>%\n  mutate(Month_num = month(acq_date)) %>%\n  mutate(Month_fac = month(acq_date, \n                           label = TRUE, \n                           abbr = FALSE))\n```\n:::\n\n\n## 5. Visualising the fire points\n\n### 5.1 Overall distribution\n\nI first map all recorded fire locations together.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf)+\n  tm_polygons() +\ntm_shape(fire_sf) +\n  tm_dots()\n```\n\n::: {.cell-output-display}\n![](hands-on-exercise-03_files/figure-html/unnamed-chunk-8-1.png){width=768}\n:::\n:::\n\n\nI run the completed map using the same code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf)+\n  tm_polygons() +\ntm_shape(fire_sf) +\n  tm_dots()\n```\n\n::: {.cell-output-display}\n![](hands-on-exercise-03_files/figure-html/unnamed-chunk-9-1.png){width=768}\n:::\n:::\n\n\nThe point map shows where fires were detected during the whole year, but it does not show whether the pattern changed over time.\n\n### 5.2 Distribution by month\n\nNext, I separate the fire events into monthly panels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf)+\n  tm_polygons() +\ntm_shape(fire_sf) +\n  tm_dots(size = 0.1) +\ntm_facets(by=\"Month_fac\", \n            free.coords=FALSE, \n            drop.units = TRUE)\n```\n\n::: {.cell-output-display}\n![](hands-on-exercise-03_files/figure-html/unnamed-chunk-10-1.png){width=768}\n:::\n:::\n\n\nI run the completed monthly map using the same code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf)+\n  tm_polygons() +\ntm_shape(fire_sf) +\n  tm_dots(size = 0.1) +\ntm_facets(by=\"Month_fac\", \n            free.coords=FALSE, \n            drop.units = TRUE)\n```\n\n::: {.cell-output-display}\n![](hands-on-exercise-03_files/figure-html/unnamed-chunk-11-1.png){width=768}\n:::\n:::\n\n\nThe monthly panels make the change much clearer. There are relatively few detections from January to June, activity rises from July, and the largest numbers occur from August to October. October has the most events, with 185 detections.\n\n## 6. Computing space-time KDE by month\n\nKernel density estimation turns the points into a smooth surface. Adding month as the time value lets me compare how the areas of higher fire activity shift during the year.\n\n### 6.1 Keeping the monthly mark\n\nOnly the month number and geometry are needed to create the point pattern object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month <- fire_sf %>% \n  select(Month_num)\n```\n:::\n\n\n### 6.2 Creating the point pattern\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_ppp <- as.ppp(fire_month)\nfire_month_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 741 points\nmarks are numeric, of storage type  'double'\nwindow: rectangle = [521564.1, 695791] x [9658137, 9828767] units\n```\n\n\n:::\n:::\n\n\nThe summary shows the number of points, their spatial window, and the range of month values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fire_month_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  741 points\nAverage intensity 2.49258e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   8.000   9.000   8.579  10.000  12.000 \n\nWindow: rectangle = [521564.1, 695791] x [9658137, 9828767] units\n                    (174200 x 170600 units)\nWindow area = 29728200000 square units\n```\n\n\n:::\n:::\n\n\nI also check whether any fire records share the same coordinates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nany(duplicated(fire_month_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n### 6.3 Adding the study window\n\nThe boundary is applied so that the analysis is limited to Kepulauan Bangka Belitung.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_owin <- fire_month_ppp[kbb_owin]\nsummary(fire_month_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  741 points\nAverage intensity 6.424519e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   8.000   9.000   8.579  10.000  12.000 \n\nWindow: polygonal boundary\n2 separate polygons (no holes)\n           vertices        area relative.area\npolygon 1     47493 11533600000      1.00e+00\npolygon 2       256      306427      2.66e-05\nenclosing rectangle: [512066.8, 705559.4] x [9655398, 9834006] units\n                     (193500 x 178600 units)\nWindow area = 11533900000 square units\nFraction of frame area: 0.334\n```\n\n\n:::\n:::\n\n\nPlotting the result is a quick check that the points and boundary line up correctly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fire_month_owin)\n```\n\n::: {.cell-output-display}\n![](hands-on-exercise-03_files/figure-html/unnamed-chunk-17-1.png){width=768}\n:::\n:::\n\n\n### 6.4 Estimating monthly density\n\n`spattemp.density()` estimates one smooth space-time density object from the point locations and their month values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_kde <- spattemp.density(fire_month_owin)\nsummary(st_kde)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 15102.47 (spatial)\n  lambda = 0.0304 (temporal)\n\nNo. of observations\n  741 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512066.8, 705559.4] x [9655398, 9834006]\n\nTemporal bound\n  [1, 12]\n\nEvaluation\n  128 x 128 x 12 trivariate lattice\n  Density range: [1.233458e-27, 8.202976e-10]\n```\n\n\n:::\n:::\n\n\n### 6.5 Comparing July to December\n\nI plot the monthly density from July to December using the same colour range, so the panels can be compared directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(7,8,9,10,11,12)\npar(mfcol=c(2,3))\nfor(i in tims){ \n  plot(st_kde, i, \n       override.par=FALSE, \n       fix.range=TRUE, \n       main=paste(\"KDE at month\",i))\n}\n```\n\n::: {.cell-output-display}\n![](hands-on-exercise-03_files/figure-html/unnamed-chunk-19-1.png){width=1152}\n:::\n:::\n\n\nThe density surfaces help distinguish a real concentration from a pile of overlapping dots. In July and August, the stronger concentration is mainly in the west and north. It then shifts towards the south and east from September to November, with the widest and strongest surface in October. By December, the density falls sharply.\n\n## 7. Computing space-time KDE by day of year\n\nUsing the day of year gives a more detailed view than grouping everything into months. Each event is now marked with a number from 1 to 365.\n\n### 7.1 Creating the point pattern\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_yday_ppp <- fire_sf %>%\n  select(DayofYear) %>%\n  as.ppp()\n```\n:::\n\n\nI apply the same study boundary and check the result.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_yday_owin <- fire_yday_ppp[kbb_owin]\nsummary(fire_yday_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  741 points\nAverage intensity 6.424519e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   10.0   213.0   258.0   245.9   287.0   352.0 \n\nWindow: polygonal boundary\n2 separate polygons (no holes)\n           vertices        area relative.area\npolygon 1     47493 11533600000      1.00e+00\npolygon 2       256      306427      2.66e-05\nenclosing rectangle: [512066.8, 705559.4] x [9655398, 9834006] units\n                     (193500 x 178600 units)\nWindow area = 11533900000 square units\nFraction of frame area: 0.334\n```\n\n\n:::\n:::\n\n\nThe 741 fire events run from day 10 to day 352. Most occur later in the year, which agrees with the monthly maps.\n\n### 7.2 Estimating daily density\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_yday <- spattemp.density(\n  fire_yday_owin)\nsummary(kde_yday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 15102.47 (spatial)\n  lambda = 6.3198 (temporal)\n\nNo. of observations\n  741 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512066.8, 705559.4] x [9655398, 9834006]\n\nTemporal bound\n  [10, 352]\n\nEvaluation\n  128 x 128 x 343 trivariate lattice\n  Density range: [3.959516e-27, 2.751287e-12]\n```\n\n\n:::\n:::\n\n\nThe automatic estimate uses a spatial bandwidth of about 15 kilometres and a temporal bandwidth of about 6 days. This gives a detailed view of short-term changes, although neighbouring days can look quite different.\n\nPlotting all 343 daily surfaces would make the page difficult to read, so I compare six dates spread across the year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndays_to_plot <- c(30, 120, 210, 240, 270, 330)\npar(mfcol = c(2, 3))\nfor (day in days_to_plot) {\n  plot(kde_yday, tselect = day,\n       override.par = FALSE,\n       fix.range = TRUE,\n       main = paste(\"KDE at day\", day))\n}\n```\n\n::: {.cell-output-display}\n![](hands-on-exercise-03_files/figure-html/unnamed-chunk-23-1.png){width=1152}\n:::\n:::\n\n\nThe early-year surfaces remain weak because there are few recorded fires. Activity becomes much clearer after day 210, with concentrations shifting across the province rather than staying in one place.\n\n## 8. Improving the bandwidths\n\nThe bandwidth controls how much nearby events are blended together. A very small value produces a patchy surface, while a very large value can hide local differences. `BOOT.spattemp()` searches for a more balanced pair of spatial and temporal bandwidths.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nBOOT.spattemp(fire_yday_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInitialising...Done.\nOptimising...\nh = 15102.47 \b; lambda = 16.84806 \nh = 16612.72 \b; lambda = 16.84806 \nh = 15102.47 \b; lambda = 1527.095 \nh = 15480.03 \b; lambda = 771.9715 \nh = 15668.81 \b; lambda = 394.4098 \nh = 15763.2 \b; lambda = 205.6289 \nh = 15810.4 \b; lambda = 111.2385 \nh = 15833.99 \b; lambda = 64.04328 \nh = 15845.79 \b; lambda = 40.44567 \nh = 15851.69 \b; lambda = 28.64687 \nh = 15863.49 \b; lambda = 5.049258 \nh = 15854.64 \b; lambda = 22.74746 \nh = 15860.54 \b; lambda = 10.94866 \nh = 15859.07 \b; lambda = 13.89836 \nh = 14348.82 \b; lambda = 13.89836 \nh = 13216.87 \b; lambda = 12.42351 \nh = 12460.27 \b; lambda = 15.37321 \nh = 10760.88 \b; lambda = 16.11064 \nh = 8875.282 \b; lambda = 11.68608 \nh = 10432.08 \b; lambda = 12.97658 \nh = 7976.084 \b; lambda = 16.66371 \nh = 9286.281 \b; lambda = 15.60366 \nh = 9615.08 \b; lambda = 18.73771 \nh = 9206.581 \b; lambda = 21.61828 \nh = 8140.483 \b; lambda = 18.23073 \nh = 8795.582 \b; lambda = 17.70071 \nh = 9124.381 \b; lambda = 20.83477 \nh = 9164.856 \b; lambda = 19.52699 \nh = 8345.358 \b; lambda = 18.48998 \nh = 9297.65 \b; lambda = 18.67578 \nh = 8928.375 \b; lambda = 16.8495 \nh = 9105.736 \b; lambda = 18.85762 \nDone.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         h     lambda \n9105.73611   18.85762 \n```\n\n\n:::\n:::\n\n\nThe selected values are about 9,106 metres and 18.9 days. Rounding them to 9,000 metres and 19 days keeps the next step simple.\n\n### 8.1 Recomputing the daily density\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_yday <- spattemp.density(fire_yday_owin,\n                             h = 9000,\n                             lambda = 19)\nsummary(kde_yday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 9000 (spatial)\n  lambda = 19 (temporal)\n\nNo. of observations\n  741 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512066.8, 705559.4] x [9655398, 9834006]\n\nTemporal bound\n  [10, 352]\n\nEvaluation\n  128 x 128 x 343 trivariate lattice\n  Density range: [2.001642e-19, 2.445724e-12]\n```\n\n\n:::\n:::\n\n\nCompared with the automatic estimate, this version uses a smaller area around each fire but a longer time window. In simple terms, it keeps more local spatial detail while reducing sudden jumps from one day to the next.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfcol = c(2, 3))\nfor (day in days_to_plot) {\n  plot(kde_yday, tselect = day,\n       override.par = FALSE,\n       fix.range = TRUE,\n       main = paste(\"Improved KDE at day\", day))\n}\n```\n\n::: {.cell-output-display}\n![](hands-on-exercise-03_files/figure-html/unnamed-chunk-26-1.png){width=1152}\n:::\n:::\n\n\nThe main seasonal story stays the same, but the later surfaces are easier to follow. The concentrations build through the middle of the year, become strongest around August to October, and then weaken towards December.\n\n### 8.2 Animating the daily pattern\n\nI use one frame every 30 days so the movement is clear without producing hundreds of nearly identical images.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanimation_days <- seq(15, 345, by = 30)\nframe_dir <- tempfile(\"kde_frames_\")\ndir.create(frame_dir)\n\nfor (i in seq_along(animation_days)) {\n  png(file.path(frame_dir, sprintf(\"frame_%02d.png\", i)),\n      width = 900, height = 700, res = 110)\n  plot(kde_yday, tselect = animation_days[i],\n       main = paste(\"KDE - Day\", animation_days[i]))\n  dev.off()\n}\n\nframes <- magick::image_read(\n  list.files(frame_dir, pattern = \"png$\", full.names = TRUE)\n)\nkde_animation <- magick::image_animate(frames, fps = 2)\nmagick::image_write(kde_animation,\n                    path = \"chap06/kde_animation.gif\")\nunlink(frame_dir, recursive = TRUE)\n```\n:::\n\n\n![Daily forest fire density across 2023](chap06/kde_animation.gif){fig-alt=\"Animated space-time kernel density surfaces showing the forest fire pattern changing across Kepulauan Bangka Belitung during 2023.\"}\n\n## 9. Checking clustering across space and time\n\nThe density maps show where activity is stronger. I now use a space-time K-function to check whether pairs of fires occur closer together than expected under spatial and temporal independence.\n\n### 9.1 Creating the space-time point object\n\nFirst, I extract the projected coordinates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- st_coordinates(fire_sf)\n```\n:::\n\n\nI combine the coordinates with the day of year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_df <- data.frame(\n  x = coords[, 1],\n  y = coords[, 2],\n  t = fire_sf$`DayofYear`)\n```\n:::\n\n\nThe data frame is then converted to the format used by `stpp`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_stpp <- as.3dpoints(fire_df)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(fire_stpp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"stpp\"\n```\n\n\n:::\n:::\n\n\nThe 3D plot uses the two horizontal axes for location and the vertical axis for day of year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fire_stpp)\n```\n\n::: {.cell-output-display}\n![](hands-on-exercise-03_files/figure-html/unnamed-chunk-32-1.png){width=768}\n:::\n:::\n\n\nThe left panel shows the spatial pattern. On the right, the cumulative line rises slowly early in the year and much faster after about day 200, confirming that most detections occurred later in 2023.\n\n### 9.2 Computing the space-time K-function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_stik <- STIKhat(fire_stpp)\n```\n:::\n\n\nTo make the result easier to interpret, I subtract the value expected under independence from the observed K-function. Positive values mean there are more nearby event pairs than expected.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk_difference <- kbb_stik$Khat - kbb_stik$Ktheo\n\nfilled.contour(\n  x = kbb_stik$dist / 1000,\n  y = kbb_stik$times,\n  z = k_difference,\n  color.palette = hcl.colors,\n  xlab = \"Spatial distance (km)\",\n  ylab = \"Time difference (days)\",\n  main = \"Observed K-function minus expected value\"\n)\n```\n\n::: {.cell-output-display}\n![](hands-on-exercise-03_files/figure-html/unnamed-chunk-34-1.png){width=768}\n:::\n:::\n\n\nThe difference is positive across the distances and time gaps shown, from about 2.9 to 43.5 kilometres and 6 to 87 days. This means the data contain more nearby fire pairs than an independent pattern would produce. Together with the density maps, it supports the view that the fires are clustered in both place and time.\n\nThis is still a descriptive comparison rather than a formal significance test. Simulation envelopes would be needed before making a stronger statistical claim.\n\n## 10. Discussion\n\nThe monthly and daily views tell a consistent story. Fire activity is limited early in 2023, begins to rise around July, and is strongest from August to October. The main concentration also moves: it is more visible in the west and north during July and August, before becoming stronger in the south and east from September to November.\n\nThe improved daily KDE makes that change easier to follow because it smooths over about 19 days while retaining more local spatial detail. The K-function comparison points in the same direction, showing more nearby fire pairs than expected under independence. The analysis can show when and where concentrations appear, but it does not identify their cause; weather, land cover, land management, and detection conditions would need separate data.\n\n[← Back to hands-on exercises](hands-on-exercise.qmd){.back-link}\n",
    "supporting": [
      "hands-on-exercise-03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}